version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demianzx_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    networks:
      - demianzxbackend_default
    volumes:
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next

networks:
  demianzxbackend_default:
    external: true

volumes:
  frontend_node_modules:
  frontend_next: